version: '3.6'
services:

  mysql_db:
    image: mysql:8.0
    restart: always
    env_file:
      - env_files/.env_mysql
    ports:
      - '13306:3306'
    volumes:
      - ./init_files/mysql:/docker-entrypoint-initdb.d

  subito_it_scraper:
    build:
      context: .
      dockerfile: ./docker_files/subito_it_scraper.Dockerfile
    env_file:
      - env_files/.env_mysql
    depends_on:
      - mysql_db
    command:
      - python
      - scrapers/subito_it/start_subito_it_scraper.py

  annunci_animali_scraper:
    build:
      context: .
      dockerfile: ./docker_files/annunci_animali_scraper.Dockerfile
    env_file:
      - env_files/.env_mysql
    depends_on:
      - mysql_db
    command:
      - python
      - scrapers/annunci_animali/start_annunci_animali_scraper.py